// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/K2Service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Grpc.services {

  /// <summary>Holder for reflection information generated from protos/K2Service.proto</summary>
  public static partial class K2ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/K2Service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static K2ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZwcm90b3MvSzJTZXJ2aWNlLnByb3RvGhNwcm90b3MvSzJEYXRhLnByb3Rv",
            "IjsKGEFzc2lnbmVkSmlvUG9pbnRzUmVxdWVzdBIQCgh1c2VybmFtZRgBIAEo",
            "CRINCgV0b2tlbhgCIAEoCSKGAQoZQXNzaWduZWRKaW9Qb2ludHNSZXNwb25z",
            "ZRIVCgRyb2xlGAEgAygOMgcuSzJSb2xlEhQKDHVzZXJJRE51bWJlchgCIAEo",
            "CRIQCgh1c2VybmFtZRgDIAEoCRINCgV0b2tlbhgEIAEoCRIbCghqaW9Qb2lu",
            "dBgFIAMoCzIJLkppb1BvaW50MlMKAksyEk0KFEdldEFzc2lnbmVkSmlvUG9p",
            "bnRzEhkuQXNzaWduZWRKaW9Qb2ludHNSZXF1ZXN0GhouQXNzaWduZWRKaW9Q",
            "b2ludHNSZXNwb25zZUIpChdjb20ubUNvbnN0cnVjdC5wcm90b2J1ZqoCDUdy",
            "cGMuc2VydmljZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Grpc.services.K2DataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.services.AssignedJioPointsRequest), global::Grpc.services.AssignedJioPointsRequest.Parser, new[]{ "Username", "Token" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.services.AssignedJioPointsResponse), global::Grpc.services.AssignedJioPointsResponse.Parser, new[]{ "Role", "UserIDNumber", "Username", "Token", "JioPoint" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AssignedJioPointsRequest : pb::IMessage<AssignedJioPointsRequest> {
    private static readonly pb::MessageParser<AssignedJioPointsRequest> _parser = new pb::MessageParser<AssignedJioPointsRequest>(() => new AssignedJioPointsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AssignedJioPointsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.services.K2ServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AssignedJioPointsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AssignedJioPointsRequest(AssignedJioPointsRequest other) : this() {
      username_ = other.username_;
      token_ = other.token_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AssignedJioPointsRequest Clone() {
      return new AssignedJioPointsRequest(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 2;
    private string token_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AssignedJioPointsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AssignedJioPointsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (Token != other.Token) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Token.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Token);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AssignedJioPointsRequest other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Token = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class AssignedJioPointsResponse : pb::IMessage<AssignedJioPointsResponse> {
    private static readonly pb::MessageParser<AssignedJioPointsResponse> _parser = new pb::MessageParser<AssignedJioPointsResponse>(() => new AssignedJioPointsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AssignedJioPointsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.services.K2ServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AssignedJioPointsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AssignedJioPointsResponse(AssignedJioPointsResponse other) : this() {
      role_ = other.role_.Clone();
      userIDNumber_ = other.userIDNumber_;
      username_ = other.username_;
      token_ = other.token_;
      jioPoint_ = other.jioPoint_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AssignedJioPointsResponse Clone() {
      return new AssignedJioPointsResponse(this);
    }

    /// <summary>Field number for the "role" field.</summary>
    public const int RoleFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Grpc.services.K2Role> _repeated_role_codec
        = pb::FieldCodec.ForEnum(10, x => (int) x, x => (global::Grpc.services.K2Role) x);
    private readonly pbc::RepeatedField<global::Grpc.services.K2Role> role_ = new pbc::RepeatedField<global::Grpc.services.K2Role>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Grpc.services.K2Role> Role {
      get { return role_; }
    }

    /// <summary>Field number for the "userIDNumber" field.</summary>
    public const int UserIDNumberFieldNumber = 2;
    private string userIDNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserIDNumber {
      get { return userIDNumber_; }
      set {
        userIDNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 3;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 4;
    private string token_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "jioPoint" field.</summary>
    public const int JioPointFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Grpc.services.JioPoint> _repeated_jioPoint_codec
        = pb::FieldCodec.ForMessage(42, global::Grpc.services.JioPoint.Parser);
    private readonly pbc::RepeatedField<global::Grpc.services.JioPoint> jioPoint_ = new pbc::RepeatedField<global::Grpc.services.JioPoint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Grpc.services.JioPoint> JioPoint {
      get { return jioPoint_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AssignedJioPointsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AssignedJioPointsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!role_.Equals(other.role_)) return false;
      if (UserIDNumber != other.UserIDNumber) return false;
      if (Username != other.Username) return false;
      if (Token != other.Token) return false;
      if(!jioPoint_.Equals(other.jioPoint_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= role_.GetHashCode();
      if (UserIDNumber.Length != 0) hash ^= UserIDNumber.GetHashCode();
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      hash ^= jioPoint_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      role_.WriteTo(output, _repeated_role_codec);
      if (UserIDNumber.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserIDNumber);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Username);
      }
      if (Token.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Token);
      }
      jioPoint_.WriteTo(output, _repeated_jioPoint_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += role_.CalculateSize(_repeated_role_codec);
      if (UserIDNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserIDNumber);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      size += jioPoint_.CalculateSize(_repeated_jioPoint_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AssignedJioPointsResponse other) {
      if (other == null) {
        return;
      }
      role_.Add(other.role_);
      if (other.UserIDNumber.Length != 0) {
        UserIDNumber = other.UserIDNumber;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      jioPoint_.Add(other.jioPoint_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            role_.AddEntriesFrom(input, _repeated_role_codec);
            break;
          }
          case 18: {
            UserIDNumber = input.ReadString();
            break;
          }
          case 26: {
            Username = input.ReadString();
            break;
          }
          case 34: {
            Token = input.ReadString();
            break;
          }
          case 42: {
            jioPoint_.AddEntriesFrom(input, _repeated_jioPoint_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
