// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/MConstruct_OfferApi.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Grpc.services {

  /// <summary>Holder for reflection information generated from protos/MConstruct_OfferApi.proto</summary>
  public static partial class MConstructOfferApiReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/MConstruct_OfferApi.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MConstructOfferApiReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBwcm90b3MvTUNvbnN0cnVjdF9PZmZlckFwaS5wcm90bxoTcHJvdG9zL0Nv",
            "bW1vbi5wcm90bxoWcHJvdG9zL09mZmVyRGF0YS5wcm90byJlCh1Qb3NzaWJs",
            "ZVNwbGl0dGVyT2ZmZXJzUmVxdWVzdBIQCgh1c2VybmFtZRgBIAEoCRINCgVm",
            "c2FJRBgCIAEoCRIjCgxzcGxpdHRlclBvcnQYAyABKA4yDS5TcGxpdHRlclBv",
            "cnQiPgobUG9zc2libGVGZWVkZXJPZmZlcnNSZXF1ZXN0EhAKCHVzZXJuYW1l",
            "GAEgASgJEg0KBWZzYUlEGAIgASgJIjAKDU9mZmVyc1JlcXVlc3QSEAoIdXNl",
            "cm5hbWUYASABKAkSDQoFZnNhSUQYAiABKAkiPwoWUG9zc2libGVPZmZlcnNS",
            "ZXNwb25zZRIlCg1wb3NzaWJsZU9mZmVyGAEgAygLMg4uUG9zc2libGVPZmZl",
            "ciIrCg5PZmZlcnNSZXNwb25zZRIZCgVvZmZlchgBIAMoCzIKLk9mZmVyRGF0",
            "YSJsCiNTcGxpdHRlclBvc3NpYmxlT2ZmZXJTdW1tYXJ5UmVxdWVzdBIQCgh1",
            "c2VybmFtZRgBIAEoCRIOCgZ0YXNrSUQYAiABKAkSIwoMc3BsaXR0ZXJQb3J0",
            "GAMgASgOMg0uU3BsaXR0ZXJQb3J0IkUKIUZlZWRlclBvc3NpYmxlT2ZmZXJT",
            "dW1tYXJ5UmVxdWVzdBIQCgh1c2VybmFtZRgBIAEoCRIOCgZ0YXNrSUQYAiAB",
            "KAkiOgoTT2ZmZXJTdW1tYXJ5UmVxdWVzdBIQCgh1c2VybmFtZRgBIAEoCRIR",
            "CglvZmZlckNvZGUYAiABKAkicgoaQ3JlYXRlU3BsaXR0ZXJPZmZlclJlcXVl",
            "c3QSEAoIdXNlcm5hbWUYASABKAkSDgoGdGFza0lEGAIgASgJEg0KBWZzYUlE",
            "GAMgASgJEiMKDHNwbGl0dGVyUG9ydBgEIAEoDjINLlNwbGl0dGVyUG9ydCJL",
            "ChhDcmVhdGVGZWVkZXJPZmZlclJlcXVlc3QSEAoIdXNlcm5hbWUYASABKAkS",
            "DgoGdGFza0lEGAIgASgJEg0KBWZzYUlEGAMgASgJIlMKDE9mZmVyRGV0YWls",
            "cxIRCglvZmZlckNvZGUYASABKAkSDgoGdGFza0lEGAIgASgJEiAKCGNhdGVn",
            "b3J5GAMgASgOMg4uT2ZmZXJDYXRlZ29yeSI5ChJBY2NlcHRPZmZlclJlcXVl",
            "c3QSEAoIdXNlcm5hbWUYASABKAkSEQoJb2ZmZXJDb2RlGAIgASgJIksKDkdl",
            "b0RhdGFSZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEicKEWxheWVyV2lzZVRh",
            "c2tMaXN0GAIgAygLMgwuVGFza1dyYXBwZXIiNwoPR2VvRGF0YVJlc3BvbnNl",
            "EiQKC2dlb0RhdGFMaXN0GAEgAygLMg8uR2VvRGF0YVdyYXBwZXIyoAYKBU9m",
            "ZmVyElQKGUdldFBvc3NpYmxlU3BsaXR0ZXJPZmZlcnMSHi5Qb3NzaWJsZVNw",
            "bGl0dGVyT2ZmZXJzUmVxdWVzdBoXLlBvc3NpYmxlT2ZmZXJzUmVzcG9uc2US",
            "UAoXR2V0UG9zc2libGVGZWVkZXJPZmZlcnMSHC5Qb3NzaWJsZUZlZWRlck9m",
            "ZmVyc1JlcXVlc3QaFy5Qb3NzaWJsZU9mZmVyc1Jlc3BvbnNlElYKH0dldFNw",
            "bGl0dGVyUG9zc2libGVPZmZlclN1bW1hcnkSJC5TcGxpdHRlclBvc3NpYmxl",
            "T2ZmZXJTdW1tYXJ5UmVxdWVzdBoNLk9mZmVyU3VtbWFyeRJSCh1HZXRGZWVk",
            "ZXJQb3NzaWJsZU9mZmVyU3VtbWFyeRIiLkZlZWRlclBvc3NpYmxlT2ZmZXJT",
            "dW1tYXJ5UmVxdWVzdBoNLk9mZmVyU3VtbWFyeRJBChNDcmVhdGVTcGxpdHRl",
            "ck9mZmVyEhsuQ3JlYXRlU3BsaXR0ZXJPZmZlclJlcXVlc3QaDS5PZmZlckRl",
            "dGFpbHMSPQoRQ3JlYXRlRmVlZGVyT2ZmZXISGS5DcmVhdGVGZWVkZXJPZmZl",
            "clJlcXVlc3QaDS5PZmZlckRldGFpbHMSLwoMR2V0QWxsT2ZmZXJzEg4uT2Zm",
            "ZXJzUmVxdWVzdBoPLk9mZmVyc1Jlc3BvbnNlEjQKEUdldFNwbGl0dGVyT2Zm",
            "ZXJzEg4uT2ZmZXJzUmVxdWVzdBoPLk9mZmVyc1Jlc3BvbnNlEjIKD0dldEZl",
            "ZWRlck9mZmVycxIOLk9mZmVyc1JlcXVlc3QaDy5PZmZlcnNSZXNwb25zZRI2",
            "Cg9HZXRPZmZlclN1bW1hcnkSFC5PZmZlclN1bW1hcnlSZXF1ZXN0Gg0uT2Zm",
            "ZXJTdW1tYXJ5Ej8KGkdldEdlb0RhdGFGb3JPZmZlclN1YlRhc2tzEg8uR2Vv",
            "RGF0YVJlcXVlc3QaEC5HZW9EYXRhUmVzcG9uc2USLQoLQWNjZXB0T2ZmZXIS",
            "Ey5BY2NlcHRPZmZlclJlcXVlc3QaCS5SZXNwb25zZUIpChdjb20ubUNvbnN0",
            "cnVjdC5wcm90b2J1ZqoCDUdycGMuc2VydmljZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Grpc.common.CommonReflection.Descriptor, global::Grpc.services.OfferDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.services.PossibleSplitterOffersRequest), global::Grpc.services.PossibleSplitterOffersRequest.Parser, new[]{ "Username", "FsaID", "SplitterPort" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.services.PossibleFeederOffersRequest), global::Grpc.services.PossibleFeederOffersRequest.Parser, new[]{ "Username", "FsaID" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.services.OffersRequest), global::Grpc.services.OffersRequest.Parser, new[]{ "Username", "FsaID" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.services.PossibleOffersResponse), global::Grpc.services.PossibleOffersResponse.Parser, new[]{ "PossibleOffer" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.services.OffersResponse), global::Grpc.services.OffersResponse.Parser, new[]{ "Offer" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.services.SplitterPossibleOfferSummaryRequest), global::Grpc.services.SplitterPossibleOfferSummaryRequest.Parser, new[]{ "Username", "TaskID", "SplitterPort" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.services.FeederPossibleOfferSummaryRequest), global::Grpc.services.FeederPossibleOfferSummaryRequest.Parser, new[]{ "Username", "TaskID" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.services.OfferSummaryRequest), global::Grpc.services.OfferSummaryRequest.Parser, new[]{ "Username", "OfferCode" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.services.CreateSplitterOfferRequest), global::Grpc.services.CreateSplitterOfferRequest.Parser, new[]{ "Username", "TaskID", "FsaID", "SplitterPort" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.services.CreateFeederOfferRequest), global::Grpc.services.CreateFeederOfferRequest.Parser, new[]{ "Username", "TaskID", "FsaID" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.services.OfferDetails), global::Grpc.services.OfferDetails.Parser, new[]{ "OfferCode", "TaskID", "Category" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.services.AcceptOfferRequest), global::Grpc.services.AcceptOfferRequest.Parser, new[]{ "Username", "OfferCode" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.services.GeoDataRequest), global::Grpc.services.GeoDataRequest.Parser, new[]{ "Username", "LayerWiseTaskList" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.services.GeoDataResponse), global::Grpc.services.GeoDataResponse.Parser, new[]{ "GeoDataList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PossibleSplitterOffersRequest : pb::IMessage<PossibleSplitterOffersRequest> {
    private static readonly pb::MessageParser<PossibleSplitterOffersRequest> _parser = new pb::MessageParser<PossibleSplitterOffersRequest>(() => new PossibleSplitterOffersRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PossibleSplitterOffersRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.services.MConstructOfferApiReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PossibleSplitterOffersRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PossibleSplitterOffersRequest(PossibleSplitterOffersRequest other) : this() {
      username_ = other.username_;
      fsaID_ = other.fsaID_;
      splitterPort_ = other.splitterPort_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PossibleSplitterOffersRequest Clone() {
      return new PossibleSplitterOffersRequest(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fsaID" field.</summary>
    public const int FsaIDFieldNumber = 2;
    private string fsaID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FsaID {
      get { return fsaID_; }
      set {
        fsaID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "splitterPort" field.</summary>
    public const int SplitterPortFieldNumber = 3;
    private global::Grpc.services.SplitterPort splitterPort_ = global::Grpc.services.SplitterPort.NoPort;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Grpc.services.SplitterPort SplitterPort {
      get { return splitterPort_; }
      set {
        splitterPort_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PossibleSplitterOffersRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PossibleSplitterOffersRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (FsaID != other.FsaID) return false;
      if (SplitterPort != other.SplitterPort) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (FsaID.Length != 0) hash ^= FsaID.GetHashCode();
      if (SplitterPort != global::Grpc.services.SplitterPort.NoPort) hash ^= SplitterPort.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (FsaID.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FsaID);
      }
      if (SplitterPort != global::Grpc.services.SplitterPort.NoPort) {
        output.WriteRawTag(24);
        output.WriteEnum((int) SplitterPort);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (FsaID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FsaID);
      }
      if (SplitterPort != global::Grpc.services.SplitterPort.NoPort) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SplitterPort);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PossibleSplitterOffersRequest other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.FsaID.Length != 0) {
        FsaID = other.FsaID;
      }
      if (other.SplitterPort != global::Grpc.services.SplitterPort.NoPort) {
        SplitterPort = other.SplitterPort;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            FsaID = input.ReadString();
            break;
          }
          case 24: {
            SplitterPort = (global::Grpc.services.SplitterPort) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PossibleFeederOffersRequest : pb::IMessage<PossibleFeederOffersRequest> {
    private static readonly pb::MessageParser<PossibleFeederOffersRequest> _parser = new pb::MessageParser<PossibleFeederOffersRequest>(() => new PossibleFeederOffersRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PossibleFeederOffersRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.services.MConstructOfferApiReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PossibleFeederOffersRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PossibleFeederOffersRequest(PossibleFeederOffersRequest other) : this() {
      username_ = other.username_;
      fsaID_ = other.fsaID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PossibleFeederOffersRequest Clone() {
      return new PossibleFeederOffersRequest(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fsaID" field.</summary>
    public const int FsaIDFieldNumber = 2;
    private string fsaID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FsaID {
      get { return fsaID_; }
      set {
        fsaID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PossibleFeederOffersRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PossibleFeederOffersRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (FsaID != other.FsaID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (FsaID.Length != 0) hash ^= FsaID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (FsaID.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FsaID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (FsaID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FsaID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PossibleFeederOffersRequest other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.FsaID.Length != 0) {
        FsaID = other.FsaID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            FsaID = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class OffersRequest : pb::IMessage<OffersRequest> {
    private static readonly pb::MessageParser<OffersRequest> _parser = new pb::MessageParser<OffersRequest>(() => new OffersRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OffersRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.services.MConstructOfferApiReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OffersRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OffersRequest(OffersRequest other) : this() {
      username_ = other.username_;
      fsaID_ = other.fsaID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OffersRequest Clone() {
      return new OffersRequest(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fsaID" field.</summary>
    public const int FsaIDFieldNumber = 2;
    private string fsaID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FsaID {
      get { return fsaID_; }
      set {
        fsaID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OffersRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OffersRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (FsaID != other.FsaID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (FsaID.Length != 0) hash ^= FsaID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (FsaID.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FsaID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (FsaID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FsaID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OffersRequest other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.FsaID.Length != 0) {
        FsaID = other.FsaID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            FsaID = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PossibleOffersResponse : pb::IMessage<PossibleOffersResponse> {
    private static readonly pb::MessageParser<PossibleOffersResponse> _parser = new pb::MessageParser<PossibleOffersResponse>(() => new PossibleOffersResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PossibleOffersResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.services.MConstructOfferApiReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PossibleOffersResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PossibleOffersResponse(PossibleOffersResponse other) : this() {
      possibleOffer_ = other.possibleOffer_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PossibleOffersResponse Clone() {
      return new PossibleOffersResponse(this);
    }

    /// <summary>Field number for the "possibleOffer" field.</summary>
    public const int PossibleOfferFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Grpc.services.PossibleOffer> _repeated_possibleOffer_codec
        = pb::FieldCodec.ForMessage(10, global::Grpc.services.PossibleOffer.Parser);
    private readonly pbc::RepeatedField<global::Grpc.services.PossibleOffer> possibleOffer_ = new pbc::RepeatedField<global::Grpc.services.PossibleOffer>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Grpc.services.PossibleOffer> PossibleOffer {
      get { return possibleOffer_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PossibleOffersResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PossibleOffersResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!possibleOffer_.Equals(other.possibleOffer_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= possibleOffer_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      possibleOffer_.WriteTo(output, _repeated_possibleOffer_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += possibleOffer_.CalculateSize(_repeated_possibleOffer_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PossibleOffersResponse other) {
      if (other == null) {
        return;
      }
      possibleOffer_.Add(other.possibleOffer_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            possibleOffer_.AddEntriesFrom(input, _repeated_possibleOffer_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class OffersResponse : pb::IMessage<OffersResponse> {
    private static readonly pb::MessageParser<OffersResponse> _parser = new pb::MessageParser<OffersResponse>(() => new OffersResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OffersResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.services.MConstructOfferApiReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OffersResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OffersResponse(OffersResponse other) : this() {
      offer_ = other.offer_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OffersResponse Clone() {
      return new OffersResponse(this);
    }

    /// <summary>Field number for the "offer" field.</summary>
    public const int OfferFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Grpc.services.OfferData> _repeated_offer_codec
        = pb::FieldCodec.ForMessage(10, global::Grpc.services.OfferData.Parser);
    private readonly pbc::RepeatedField<global::Grpc.services.OfferData> offer_ = new pbc::RepeatedField<global::Grpc.services.OfferData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Grpc.services.OfferData> Offer {
      get { return offer_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OffersResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OffersResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!offer_.Equals(other.offer_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= offer_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      offer_.WriteTo(output, _repeated_offer_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += offer_.CalculateSize(_repeated_offer_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OffersResponse other) {
      if (other == null) {
        return;
      }
      offer_.Add(other.offer_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            offer_.AddEntriesFrom(input, _repeated_offer_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SplitterPossibleOfferSummaryRequest : pb::IMessage<SplitterPossibleOfferSummaryRequest> {
    private static readonly pb::MessageParser<SplitterPossibleOfferSummaryRequest> _parser = new pb::MessageParser<SplitterPossibleOfferSummaryRequest>(() => new SplitterPossibleOfferSummaryRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SplitterPossibleOfferSummaryRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.services.MConstructOfferApiReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SplitterPossibleOfferSummaryRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SplitterPossibleOfferSummaryRequest(SplitterPossibleOfferSummaryRequest other) : this() {
      username_ = other.username_;
      taskID_ = other.taskID_;
      splitterPort_ = other.splitterPort_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SplitterPossibleOfferSummaryRequest Clone() {
      return new SplitterPossibleOfferSummaryRequest(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "taskID" field.</summary>
    public const int TaskIDFieldNumber = 2;
    private string taskID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TaskID {
      get { return taskID_; }
      set {
        taskID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "splitterPort" field.</summary>
    public const int SplitterPortFieldNumber = 3;
    private global::Grpc.services.SplitterPort splitterPort_ = global::Grpc.services.SplitterPort.NoPort;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Grpc.services.SplitterPort SplitterPort {
      get { return splitterPort_; }
      set {
        splitterPort_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SplitterPossibleOfferSummaryRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SplitterPossibleOfferSummaryRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (TaskID != other.TaskID) return false;
      if (SplitterPort != other.SplitterPort) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (TaskID.Length != 0) hash ^= TaskID.GetHashCode();
      if (SplitterPort != global::Grpc.services.SplitterPort.NoPort) hash ^= SplitterPort.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (TaskID.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TaskID);
      }
      if (SplitterPort != global::Grpc.services.SplitterPort.NoPort) {
        output.WriteRawTag(24);
        output.WriteEnum((int) SplitterPort);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (TaskID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaskID);
      }
      if (SplitterPort != global::Grpc.services.SplitterPort.NoPort) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SplitterPort);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SplitterPossibleOfferSummaryRequest other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.TaskID.Length != 0) {
        TaskID = other.TaskID;
      }
      if (other.SplitterPort != global::Grpc.services.SplitterPort.NoPort) {
        SplitterPort = other.SplitterPort;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            TaskID = input.ReadString();
            break;
          }
          case 24: {
            SplitterPort = (global::Grpc.services.SplitterPort) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class FeederPossibleOfferSummaryRequest : pb::IMessage<FeederPossibleOfferSummaryRequest> {
    private static readonly pb::MessageParser<FeederPossibleOfferSummaryRequest> _parser = new pb::MessageParser<FeederPossibleOfferSummaryRequest>(() => new FeederPossibleOfferSummaryRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FeederPossibleOfferSummaryRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.services.MConstructOfferApiReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FeederPossibleOfferSummaryRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FeederPossibleOfferSummaryRequest(FeederPossibleOfferSummaryRequest other) : this() {
      username_ = other.username_;
      taskID_ = other.taskID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FeederPossibleOfferSummaryRequest Clone() {
      return new FeederPossibleOfferSummaryRequest(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "taskID" field.</summary>
    public const int TaskIDFieldNumber = 2;
    private string taskID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TaskID {
      get { return taskID_; }
      set {
        taskID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FeederPossibleOfferSummaryRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FeederPossibleOfferSummaryRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (TaskID != other.TaskID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (TaskID.Length != 0) hash ^= TaskID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (TaskID.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TaskID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (TaskID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaskID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FeederPossibleOfferSummaryRequest other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.TaskID.Length != 0) {
        TaskID = other.TaskID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            TaskID = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class OfferSummaryRequest : pb::IMessage<OfferSummaryRequest> {
    private static readonly pb::MessageParser<OfferSummaryRequest> _parser = new pb::MessageParser<OfferSummaryRequest>(() => new OfferSummaryRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OfferSummaryRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.services.MConstructOfferApiReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OfferSummaryRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OfferSummaryRequest(OfferSummaryRequest other) : this() {
      username_ = other.username_;
      offerCode_ = other.offerCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OfferSummaryRequest Clone() {
      return new OfferSummaryRequest(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "offerCode" field.</summary>
    public const int OfferCodeFieldNumber = 2;
    private string offerCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OfferCode {
      get { return offerCode_; }
      set {
        offerCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OfferSummaryRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OfferSummaryRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (OfferCode != other.OfferCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (OfferCode.Length != 0) hash ^= OfferCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (OfferCode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OfferCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (OfferCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OfferCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OfferSummaryRequest other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.OfferCode.Length != 0) {
        OfferCode = other.OfferCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            OfferCode = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CreateSplitterOfferRequest : pb::IMessage<CreateSplitterOfferRequest> {
    private static readonly pb::MessageParser<CreateSplitterOfferRequest> _parser = new pb::MessageParser<CreateSplitterOfferRequest>(() => new CreateSplitterOfferRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateSplitterOfferRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.services.MConstructOfferApiReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateSplitterOfferRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateSplitterOfferRequest(CreateSplitterOfferRequest other) : this() {
      username_ = other.username_;
      taskID_ = other.taskID_;
      fsaID_ = other.fsaID_;
      splitterPort_ = other.splitterPort_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateSplitterOfferRequest Clone() {
      return new CreateSplitterOfferRequest(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "taskID" field.</summary>
    public const int TaskIDFieldNumber = 2;
    private string taskID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TaskID {
      get { return taskID_; }
      set {
        taskID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fsaID" field.</summary>
    public const int FsaIDFieldNumber = 3;
    private string fsaID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FsaID {
      get { return fsaID_; }
      set {
        fsaID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "splitterPort" field.</summary>
    public const int SplitterPortFieldNumber = 4;
    private global::Grpc.services.SplitterPort splitterPort_ = global::Grpc.services.SplitterPort.NoPort;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Grpc.services.SplitterPort SplitterPort {
      get { return splitterPort_; }
      set {
        splitterPort_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateSplitterOfferRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateSplitterOfferRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (TaskID != other.TaskID) return false;
      if (FsaID != other.FsaID) return false;
      if (SplitterPort != other.SplitterPort) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (TaskID.Length != 0) hash ^= TaskID.GetHashCode();
      if (FsaID.Length != 0) hash ^= FsaID.GetHashCode();
      if (SplitterPort != global::Grpc.services.SplitterPort.NoPort) hash ^= SplitterPort.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (TaskID.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TaskID);
      }
      if (FsaID.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FsaID);
      }
      if (SplitterPort != global::Grpc.services.SplitterPort.NoPort) {
        output.WriteRawTag(32);
        output.WriteEnum((int) SplitterPort);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (TaskID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaskID);
      }
      if (FsaID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FsaID);
      }
      if (SplitterPort != global::Grpc.services.SplitterPort.NoPort) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SplitterPort);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateSplitterOfferRequest other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.TaskID.Length != 0) {
        TaskID = other.TaskID;
      }
      if (other.FsaID.Length != 0) {
        FsaID = other.FsaID;
      }
      if (other.SplitterPort != global::Grpc.services.SplitterPort.NoPort) {
        SplitterPort = other.SplitterPort;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            TaskID = input.ReadString();
            break;
          }
          case 26: {
            FsaID = input.ReadString();
            break;
          }
          case 32: {
            SplitterPort = (global::Grpc.services.SplitterPort) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CreateFeederOfferRequest : pb::IMessage<CreateFeederOfferRequest> {
    private static readonly pb::MessageParser<CreateFeederOfferRequest> _parser = new pb::MessageParser<CreateFeederOfferRequest>(() => new CreateFeederOfferRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateFeederOfferRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.services.MConstructOfferApiReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateFeederOfferRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateFeederOfferRequest(CreateFeederOfferRequest other) : this() {
      username_ = other.username_;
      taskID_ = other.taskID_;
      fsaID_ = other.fsaID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateFeederOfferRequest Clone() {
      return new CreateFeederOfferRequest(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "taskID" field.</summary>
    public const int TaskIDFieldNumber = 2;
    private string taskID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TaskID {
      get { return taskID_; }
      set {
        taskID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fsaID" field.</summary>
    public const int FsaIDFieldNumber = 3;
    private string fsaID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FsaID {
      get { return fsaID_; }
      set {
        fsaID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateFeederOfferRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateFeederOfferRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (TaskID != other.TaskID) return false;
      if (FsaID != other.FsaID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (TaskID.Length != 0) hash ^= TaskID.GetHashCode();
      if (FsaID.Length != 0) hash ^= FsaID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (TaskID.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TaskID);
      }
      if (FsaID.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FsaID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (TaskID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaskID);
      }
      if (FsaID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FsaID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateFeederOfferRequest other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.TaskID.Length != 0) {
        TaskID = other.TaskID;
      }
      if (other.FsaID.Length != 0) {
        FsaID = other.FsaID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            TaskID = input.ReadString();
            break;
          }
          case 26: {
            FsaID = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class OfferDetails : pb::IMessage<OfferDetails> {
    private static readonly pb::MessageParser<OfferDetails> _parser = new pb::MessageParser<OfferDetails>(() => new OfferDetails());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OfferDetails> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.services.MConstructOfferApiReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OfferDetails() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OfferDetails(OfferDetails other) : this() {
      offerCode_ = other.offerCode_;
      taskID_ = other.taskID_;
      category_ = other.category_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OfferDetails Clone() {
      return new OfferDetails(this);
    }

    /// <summary>Field number for the "offerCode" field.</summary>
    public const int OfferCodeFieldNumber = 1;
    private string offerCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OfferCode {
      get { return offerCode_; }
      set {
        offerCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "taskID" field.</summary>
    public const int TaskIDFieldNumber = 2;
    private string taskID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TaskID {
      get { return taskID_; }
      set {
        taskID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "category" field.</summary>
    public const int CategoryFieldNumber = 3;
    private global::Grpc.services.OfferCategory category_ = global::Grpc.services.OfferCategory.NoCategory;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Grpc.services.OfferCategory Category {
      get { return category_; }
      set {
        category_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OfferDetails);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OfferDetails other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OfferCode != other.OfferCode) return false;
      if (TaskID != other.TaskID) return false;
      if (Category != other.Category) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (OfferCode.Length != 0) hash ^= OfferCode.GetHashCode();
      if (TaskID.Length != 0) hash ^= TaskID.GetHashCode();
      if (Category != global::Grpc.services.OfferCategory.NoCategory) hash ^= Category.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (OfferCode.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OfferCode);
      }
      if (TaskID.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TaskID);
      }
      if (Category != global::Grpc.services.OfferCategory.NoCategory) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Category);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (OfferCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OfferCode);
      }
      if (TaskID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaskID);
      }
      if (Category != global::Grpc.services.OfferCategory.NoCategory) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Category);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OfferDetails other) {
      if (other == null) {
        return;
      }
      if (other.OfferCode.Length != 0) {
        OfferCode = other.OfferCode;
      }
      if (other.TaskID.Length != 0) {
        TaskID = other.TaskID;
      }
      if (other.Category != global::Grpc.services.OfferCategory.NoCategory) {
        Category = other.Category;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OfferCode = input.ReadString();
            break;
          }
          case 18: {
            TaskID = input.ReadString();
            break;
          }
          case 24: {
            Category = (global::Grpc.services.OfferCategory) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class AcceptOfferRequest : pb::IMessage<AcceptOfferRequest> {
    private static readonly pb::MessageParser<AcceptOfferRequest> _parser = new pb::MessageParser<AcceptOfferRequest>(() => new AcceptOfferRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AcceptOfferRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.services.MConstructOfferApiReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AcceptOfferRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AcceptOfferRequest(AcceptOfferRequest other) : this() {
      username_ = other.username_;
      offerCode_ = other.offerCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AcceptOfferRequest Clone() {
      return new AcceptOfferRequest(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "offerCode" field.</summary>
    public const int OfferCodeFieldNumber = 2;
    private string offerCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OfferCode {
      get { return offerCode_; }
      set {
        offerCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AcceptOfferRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AcceptOfferRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (OfferCode != other.OfferCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (OfferCode.Length != 0) hash ^= OfferCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (OfferCode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OfferCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (OfferCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OfferCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AcceptOfferRequest other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.OfferCode.Length != 0) {
        OfferCode = other.OfferCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            OfferCode = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GeoDataRequest : pb::IMessage<GeoDataRequest> {
    private static readonly pb::MessageParser<GeoDataRequest> _parser = new pb::MessageParser<GeoDataRequest>(() => new GeoDataRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GeoDataRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.services.MConstructOfferApiReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GeoDataRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GeoDataRequest(GeoDataRequest other) : this() {
      username_ = other.username_;
      layerWiseTaskList_ = other.layerWiseTaskList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GeoDataRequest Clone() {
      return new GeoDataRequest(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "layerWiseTaskList" field.</summary>
    public const int LayerWiseTaskListFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Grpc.services.TaskWrapper> _repeated_layerWiseTaskList_codec
        = pb::FieldCodec.ForMessage(18, global::Grpc.services.TaskWrapper.Parser);
    private readonly pbc::RepeatedField<global::Grpc.services.TaskWrapper> layerWiseTaskList_ = new pbc::RepeatedField<global::Grpc.services.TaskWrapper>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Grpc.services.TaskWrapper> LayerWiseTaskList {
      get { return layerWiseTaskList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GeoDataRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GeoDataRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if(!layerWiseTaskList_.Equals(other.layerWiseTaskList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      hash ^= layerWiseTaskList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      layerWiseTaskList_.WriteTo(output, _repeated_layerWiseTaskList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      size += layerWiseTaskList_.CalculateSize(_repeated_layerWiseTaskList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GeoDataRequest other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      layerWiseTaskList_.Add(other.layerWiseTaskList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            layerWiseTaskList_.AddEntriesFrom(input, _repeated_layerWiseTaskList_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GeoDataResponse : pb::IMessage<GeoDataResponse> {
    private static readonly pb::MessageParser<GeoDataResponse> _parser = new pb::MessageParser<GeoDataResponse>(() => new GeoDataResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GeoDataResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.services.MConstructOfferApiReflection.Descriptor.MessageTypes[13]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GeoDataResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GeoDataResponse(GeoDataResponse other) : this() {
      geoDataList_ = other.geoDataList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GeoDataResponse Clone() {
      return new GeoDataResponse(this);
    }

    /// <summary>Field number for the "geoDataList" field.</summary>
    public const int GeoDataListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Grpc.services.GeoDataWrapper> _repeated_geoDataList_codec
        = pb::FieldCodec.ForMessage(10, global::Grpc.services.GeoDataWrapper.Parser);
    private readonly pbc::RepeatedField<global::Grpc.services.GeoDataWrapper> geoDataList_ = new pbc::RepeatedField<global::Grpc.services.GeoDataWrapper>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Grpc.services.GeoDataWrapper> GeoDataList {
      get { return geoDataList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GeoDataResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GeoDataResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!geoDataList_.Equals(other.geoDataList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= geoDataList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      geoDataList_.WriteTo(output, _repeated_geoDataList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += geoDataList_.CalculateSize(_repeated_geoDataList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GeoDataResponse other) {
      if (other == null) {
        return;
      }
      geoDataList_.Add(other.geoDataList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            geoDataList_.AddEntriesFrom(input, _repeated_geoDataList_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
